#!/usr/bin/env python3
"""
update-index.py — Directory Map Indexer
Generated by the directory-map Claude skill.

Usage:
    python update-index.py [directory]

If no directory is provided, indexes ROOT_PATH (set below).
Outputs index.json in the root of the indexed directory.

Customise the three sections marked ### CONFIGURE below.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# ### CONFIGURE 1/3 — Root path (overridden by CLI arg if provided)
# ─────────────────────────────────────────────────────────────────────────────
ROOT_PATH = Path("/Users/melsawah1/Developer/wos-bot")
if not ROOT_PATH.exists():  # moved/cloned checkout: fall back to this file's own dir
    ROOT_PATH = Path(__file__).parent.resolve()

# ─────────────────────────────────────────────────────────────────────────────
# ### CONFIGURE 2/3 — Directories to skip entirely (never traverse into these)
# ─────────────────────────────────────────────────────────────────────────────
SKIP_DIRS = {
    "node_modules", ".git", ".next", "__pycache__", ".vercel",
    ".turbo", "dist", ".cache", "venv", ".env", ".tox", ".pytest_cache",
    "target",       # Rust/Java build output
    "build",        # Generic build output
    ".gradle",
    ".idea",        # JetBrains IDE
    ".vscode",      # VS Code settings (optional — remove if you want to index these)
    # --- wos-bot specific ---
    ".venv",          # 900MB+ of paddle/opencv wheels; never index
    ".ruff_cache",
    ".mypy_cache",
}

# ─────────────────────────────────────────────────────────────────────────────
# ### CONFIGURE 3/3 — Known projects with their domain and metadata
# Claude pre-populates this with projects discovered during the initial scan.
# ─────────────────────────────────────────────────────────────────────────────
PROJECT_REGISTRY: dict[str, dict] = {
    # --- Domain B: the runnable bot, module by module ---
    "Main":        {"id": "main-loop",     "domain": "B", "status": "dev",
                    "role": "entry_point_task_runner"},
    "core":        {"id": "core",          "domain": "B", "status": "dev",
                    "role": "device_ocr_vision_capability"},
    "usecases":    {"id": "usecases",      "domain": "B", "status": "dev",
                    "role": "per_task_routines"},
    "cmd_program": {"id": "cmd-program",   "domain": "B", "status": "dev",
                    "role": "adb_scrcpy_io"},
    "tests":       {"id": "tests",         "domain": "B", "status": "dev",
                    "role": "offline_pytest_suite"},

    # --- Domain D: data, telemetry, and the scripts that read it ---
    "scripts":     {"id": "analysis",      "domain": "D", "status": "active",
                    "role": "burnin_and_capability_reports"},
    "logs":        {"id": "burnin-log",    "domain": "D", "status": "active",
                    "role": "ocr_shadow_check_jsonl"},
    "db":          {"id": "state-store",   "domain": "D", "status": "active",
                    "role": "player_profiles_completion_log"},

    # --- Domain C: the written record ---
    "docs":        {"id": "port-record",   "domain": "C", "status": "reference",
                    "role": "port_decisions_designs_knowledge"},

    # --- Domain E: session tooling output ---
    ".gstack":     {"id": "gstack",        "domain": "E", "status": "generated",
                    "role": "qa_report_output"},

    # --- Domain F: runtime visual/ROI assets ---
    "references":  {"id": "screen-assets", "domain": "F", "status": "active",
                    "role": "icon_templates_and_roi_json"},
    "frames":      {"id": "frames",        "domain": "F", "status": "scratch",
                    "role": "captured_framebuffer"},

    # --- Domain G: superseded code kept for reference ---
    "test":        {"id": "legacy-scratch","domain": "G", "status": "dormant",
                    "role": "pre_port_manual_scripts"},
    "backup":      {"id": "ocr-backup",    "domain": "G", "status": "dormant",
                    "role": "pre_vision_swap_ocr_copies"},
}

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────
MAX_DEPTH = 5
SKIP_EXTENSIONS = {".lock"}  # file extensions to exclude

PROJECT_CONFIG_FILES = {
    "package.json", "pyproject.toml", "Cargo.toml", "go.mod",
    "pom.xml", "build.gradle", "composer.json", "Gemfile",
}

DEPLOY_SIGNAL_FILES = {
    "vercel.json", "netlify.toml", "fly.toml", "railway.json",
    "Procfile", "Dockerfile", "docker-compose.yml",
}

CLAUDE_FILES = {"CLAUDE.md", "agent-context.md", "AGENTS.md"}

DOMAIN_LABELS = {
    "A": "Live / Published",
    "B": "Active Development",
    "C": "Concept / Planning",
    "D": "Data & Research Pipelines",
    "E": "Shared Infrastructure",
    "F": "Content & Creative Assets",
    "G": "Reference & Archived",
}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def rel(path: Path, root: Path) -> str:
    """Return a forward-slash relative path string."""
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def safe_stat(path: Path) -> dict:
    """Return size_kb and last_modified without raising on permission errors."""
    try:
        s = path.stat()
        return {
            "size_kb": round(s.st_size / 1024, 2),
            "last_modified": datetime.fromtimestamp(s.st_mtime, tz=timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
        }
    except OSError:
        return {"size_kb": 0, "last_modified": ""}


def parse_package_json(path: Path) -> dict | None:
    """Extract name, version, framework, and top scripts from package.json."""
    try:
        data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
        deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
        framework = ""
        if "next" in deps:
            framework = f"Next.js {deps['next'].lstrip('^~')}"
        elif "@nestjs/core" in deps:
            framework = f"NestJS {deps['@nestjs/core'].lstrip('^~')}"
        elif "react" in deps:
            framework = f"React {deps['react'].lstrip('^~')}"
        elif "express" in deps:
            framework = f"Express {deps['express'].lstrip('^~')}"
        return {
            "name": data.get("name", ""),
            "version": data.get("version", ""),
            "framework": framework,
            "scripts": list(data.get("scripts", {}).keys())[:8],
            "top_deps": list(deps.keys())[:5],
        }
    except Exception:
        return None


def parse_pyproject(path: Path) -> dict | None:
    """Minimal pyproject.toml parser (no external deps required)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        name = ""
        for line in text.splitlines():
            if line.strip().startswith("name"):
                name = line.split("=", 1)[-1].strip().strip('"\'')
                break
        framework = ""
        if "fastapi" in text.lower():
            framework = "FastAPI"
        elif "flask" in text.lower():
            framework = "Flask"
        elif "django" in text.lower():
            framework = "Django"
        return {"name": name, "framework": framework}
    except Exception:
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Core traversal
# ─────────────────────────────────────────────────────────────────────────────

def traverse(
    path: Path,
    root: Path,
    depth: int,
    dirs_out: list,
    files_out: list,
    projects_out: list,
    errors_out: list,
    visited: set,
):
    if depth > MAX_DEPTH:
        return

    # Symlink loop guard
    try:
        real = path.resolve()
    except OSError:
        real = path
    if real in visited:
        return
    visited.add(real)

    try:
        children = sorted(path.iterdir())
    except PermissionError as e:
        errors_out.append({"type": "AccessDenied", "path": rel(path, root), "message": str(e)})
        return
    except OSError as e:
        errors_out.append({"type": "OSError", "path": rel(path, root), "message": str(e)})
        return

    for child in children:
        if child.is_dir():
            if child.name in SKIP_DIRS:
                continue

            stat = safe_stat(child)
            has_claude = (child / "CLAUDE.md").exists() or (child / "agent-context.md").exists()
            has_pkg = (child / "package.json").exists()
            has_git = (child / ".git").exists()
            has_pyproject = (child / "pyproject.toml").exists()
            has_deploy = any((child / f).exists() for f in DEPLOY_SIGNAL_FILES)

            pkg_meta = parse_package_json(child / "package.json") if has_pkg else None
            py_meta = parse_pyproject(child / "pyproject.toml") if has_pyproject else None

            domain_info = PROJECT_REGISTRY.get(child.name)

            dir_entry: dict = {
                "name": child.name,
                "path": rel(child, root),
                "depth": depth,
                "claude_aware": has_claude,
                "has_package_json": has_pkg,
                "has_git": has_git,
                "has_pyproject": has_pyproject,
                "has_deploy_config": has_deploy,
                "last_modified": stat["last_modified"],
                "domain": domain_info["domain"] if domain_info else None,
            }
            dirs_out.append(dir_entry)

            if domain_info:
                proj_entry = {
                    **domain_info,
                    "name": child.name,
                    "path": rel(child, root),
                    "claude_aware": has_claude,
                    "has_git": has_git,
                    "framework": (pkg_meta or py_meta or {}).get("framework", ""),
                    "pkg_name": (pkg_meta or {}).get("name", ""),
                }
                projects_out.append(proj_entry)

            traverse(child, root, depth + 1, dirs_out, files_out, projects_out, errors_out, visited)

        else:
            if child.suffix.lower() in SKIP_EXTENSIONS:
                continue
            stat = safe_stat(child)
            files_out.append({
                "name": child.name,
                "ext": child.suffix.lower(),
                "path": rel(child, root),
                "size_kb": stat["size_kb"],
                "last_modified": stat["last_modified"],
                "depth": depth,
            })


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT_PATH
    output_file = root / "index.json"

    print(f"Indexing {root} (max depth {MAX_DEPTH})...")
    t0 = time.time()

    dirs: list = []
    files: list = []
    projects: list = []
    errors: list = []
    visited: set = set()

    traverse(root, root, 0, dirs, files, projects, errors, visited)

    elapsed_ms = round((time.time() - t0) * 1000)

    ext_counts: dict[str, int] = {}
    for f in files:
        ext_counts[f["ext"]] = ext_counts.get(f["ext"], 0) + 1
    ext_summary = sorted(
        [{"ext": k, "count": v} for k, v in ext_counts.items()],
        key=lambda x: -x["count"],
    )[:20]

    domain_summary = []
    for dk, dl in DOMAIN_LABELS.items():
        domain_summary.append({
            "id": dk,
            "label": dl,
            "project_count": sum(1 for p in projects if p.get("domain") == dk),
            "dir_count": sum(1 for d in dirs if d.get("domain") == dk),
        })

    output = {
        "generated": datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "root": str(root),
        "scan_depth": MAX_DEPTH,
        "duration_ms": elapsed_ms,
        "total_dirs": len(dirs),
        "total_files": len(files),
        "total_projects": len(projects),
        "error_count": len(errors),
        "domains": domain_summary,
        "projects": projects,
        "extension_summary": ext_summary,
        "top_level_dirs": [d for d in dirs if d["depth"] == 0],
        "claude_aware_dirs": [
            {k: d[k] for k in ("name", "path", "depth", "domain")}
            for d in dirs if d.get("claude_aware")
        ],
        "errors": errors,
    }

    with open(output_file, "w", encoding="utf-8") as fh:
        json.dump(output, fh, indent=2, ensure_ascii=False)

    print(f"\n[OK] index.json written to: {output_file}")
    print(f"  Dirs:     {len(dirs)}")
    print(f"  Files:    {len(files)}")
    print(f"  Projects: {len(projects)}")
    print(f"  Errors:   {len(errors)}")
    print(f"  Time:     {elapsed_ms}ms")

    if errors:
        print("\nErrors during scan:")
        for e in errors:
            print(f"  [{e['type']}] {e['path']}")
        sys.exit(1)


if __name__ == "__main__":
    main()
